name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.0", "8.1", "8.2", "8.3", "8.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "tag=${{ matrix.version }}-nightly" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" != "master" && "${GITHUB_REF_NAME}" != "main" ]]; then
            echo "tag=${{ matrix.version }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ matrix.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.version }}"
          push: true
          tags: ${{ vars.DOCKERHUB_REPO }}:${{ steps.vars.outputs.tag }}
          platforms: linux/amd64,linux/arm64